In [7]:
import pandas as pd
df = pd.read_excel("/content/E-Commerce Sales Analytics.xlsx")
df

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
0,10001,2022-01-01,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.20
1,10002,2022-01-02,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10
2,10003,2022-01-03,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,644.35
3,10004,2022-01-04,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2569.90
4,10005,2022-01-05,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,468.56
...,...,...,...,...,...,...,...,...,...,...,...,...
4995,14996,2035-09-05,1289,Clothing,West,2,371.74,0.27,COD,3,2.3,542.74
4996,14997,2035-09-06,1294,Beauty,North,3,553.67,0.14,COD,11,2.2,1428.47
4997,14998,2035-09-07,1450,Beauty,West,3,77.22,0.24,Wallet,6,3.4,176.06
4998,14999,2035-09-08,1903,Electronics,South,4,138.41,0.21,COD,4,2.8,437.38
4999,15000,2035-09-09,1214,Home,East,7,231.58,0.34,COD,5,3.9,1069.90

In [17]:
import pandas as pd
df2 = pd.read_excel("/content/E-Commerce Sales Analytics.xlsx")
df2

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
0,10001,2022-01-01,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.20
1,10002,2022-01-02,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10
2,10003,2022-01-03,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,644.35
3,10004,2022-01-04,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2569.90
4,10005,2022-01-05,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,468.56
...,...,...,...,...,...,...,...,...,...,...,...,...
4995,14996,2035-09-05,1289,Clothing,West,2,371.74,0.27,COD,3,2.3,542.74
4996,14997,2035-09-06,1294,Beauty,North,3,553.67,0.14,COD,11,2.2,1428.47
4997,14998,2035-09-07,1450,Beauty,West,3,77.22,0.24,Wallet,6,3.4,176.06
4998,14999,2035-09-08,1903,Electronics,South,4,138.41,0.21,COD,4,2.8,437.38
4999,15000,2035-09-09,1214,Home,East,7,231.58,0.34,COD,5,3.9,1069.90

In [10]:
df[df['customer_id'] <= 1050]

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
7,10008,2022-01-08,1020,Beauty,North,6,265.71,0.13,Card,2,3.7,1387.01
34,10035,2022-02-04,1021,Electronics,West,2,511.91,0.19,COD,9,1.5,829.29
61,10062,2022-03-03,1020,Clothing,East,7,113.52,0.15,COD,8,1.3,675.44
68,10069,2022-03-10,1013,Home,North,4,546.26,0.17,COD,11,3.8,1813.58
83,10084,2022-03-25,1034,Clothing,North,1,584.98,0.23,COD,6,2.0,450.43
...,...,...,...,...,...,...,...,...,...,...,...,...
4920,14921,2035-06-22,1018,Home,South,1,266.11,0.07,Card,2,3.1,247.48
4932,14933,2035-07-04,1024,Home,West,7,507.74,0.20,COD,10,2.3,2843.34
4934,14935,2035-07-06,1000,Electronics,East,2,595.41,0.01,COD,1,4.0,1178.91
4971,14972,2035-08-12,1044,Electronics,West,5,471.78,0.25,Card,11,3.2,1769.17
4990,14991,2035-08-31,1012,Home,East,1,265.48,0.32,Card,10,2.9,180.53

In [13]:
specific_category= ["Clothing", "Electronics"]
df[df['product_category'].isin(specific_category)]

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
1,10002,2022-01-02,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10
3,10004,2022-01-04,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2569.90
4,10005,2022-01-05,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,468.56
5,10006,2022-01-06,1071,Electronics,West,2,264.44,0.20,Card,3,3.3,423.10
6,10007,2022-01-07,1700,Clothing,South,6,564.60,0.23,Card,1,1.8,2608.45
...,...,...,...,...,...,...,...,...,...,...,...,...
4988,14989,2035-08-29,1449,Clothing,West,1,559.73,0.28,Card,1,4.4,403.01
4989,14990,2035-08-30,1473,Clothing,East,4,245.98,0.12,Card,3,2.1,865.85
4993,14994,2035-09-03,1926,Electronics,West,1,113.63,0.14,COD,4,1.0,97.72
4995,14996,2035-09-05,1289,Clothing,West,2,371.74,0.27,COD,3,2.3,542.74
4998,14999,2035-09-08,1903,Electronics,South,4,138.41,0.21,COD,4,2.8,437.38

In [14]:
df[df['product_category'].str.contains("thing")]

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
1,10002,2022-01-02,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10
4,10005,2022-01-05,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,468.56
6,10007,2022-01-07,1700,Clothing,South,6,564.60,0.23,Card,1,1.8,2608.45
8,10009,2022-01-09,1614,Clothing,South,6,224.65,0.27,Card,2,1.4,983.97
9,10010,2022-01-10,1121,Clothing,West,4,272.71,0.06,Card,10,4.5,1025.39
...,...,...,...,...,...,...,...,...,...,...,...,...
4985,14986,2035-08-26,1357,Clothing,East,2,543.38,0.32,Card,10,4.0,739.00
4986,14987,2035-08-27,1187,Clothing,North,6,27.28,0.34,Wallet,7,3.2,108.03
4988,14989,2035-08-29,1449,Clothing,West,1,559.73,0.28,Card,1,4.4,403.01
4989,14990,2035-08-30,1473,Clothing,East,4,245.98,0.12,Card,3,2.1,865.85
4995,14996,2035-09-05,1289,Clothing,West,2,371.74,0.27,COD,3,2.3,542.74

In [15]:
df = df.set_index("region")
df

,order_id,order_date,customer_id,product_category,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
region,,,,,,,,,,,
South,10001,2022-01-01,1102,Beauty,7,373.65,0.28,Wallet,10,4.7,1883.20
South,10002,2022-01-02,1435,Clothing,7,47.74,0.09,Card,6,3.9,304.10
East,10003,2022-01-03,1860,Beauty,3,311.28,0.31,COD,6,2.5,644.35
West,10004,2022-01-04,1270,Electronics,5,524.47,0.02,Wallet,6,1.6,2569.90
West,10005,2022-01-05,1106,Clothing,5,139.87,0.33,Wallet,4,4.9,468.56
...,...,...,...,...,...,...,...,...,...,...,...
West,14996,2035-09-05,1289,Clothing,2,371.74,0.27,COD,3,2.3,542.74
North,14997,2035-09-06,1294,Beauty,3,553.67,0.14,COD,11,2.2,1428.47
West,14998,2035-09-07,1450,Beauty,3,77.22,0.24,Wallet,6,3.4,176.06
South,14999,2035-09-08,1903,Electronics,4,138.41,0.21,COD,4,2.8,437.38
East,15000,2035-09-09,1214,Home,7,231.58,0.34,COD,5,3.9,1069.90

In [16]:
df.filter(items =['product_category', 'payment_method'])

       product_category payment_method
region
South            Beauty         Wallet
South          Clothing           Card
East             Beauty            COD
West        Electronics         Wallet
West           Clothing         Wallet
...                 ...            ...
West           Clothing            COD
North            Beauty            COD
West             Beauty         Wallet
South       Electronics            COD
East               Home            COD

[5000 rows x 2 columns]

In [22]:
df2[df2['quantity'] <= 3].sort_values(by="quantity", ascending=False)

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
4967,14968,2035-08-08,1972,Home,East,3,125.72,0.35,Card,9,4.1,245.15
44,10045,2022-02-14,1699,Home,East,3,31.16,0.00,Wallet,6,3.3,93.48
36,10037,2022-02-06,1747,Clothing,South,3,186.01,0.13,Card,4,4.4,485.49
18,10019,2022-01-19,1663,Home,West,3,434.87,0.28,Wallet,4,2.5,939.32
16,10017,2022-01-17,1099,Clothing,North,3,213.01,0.05,Wallet,11,4.2,607.08
...,...,...,...,...,...,...,...,...,...,...,...,...
43,10044,2022-02-13,1475,Electronics,North,1,17.05,0.09,Card,1,3.8,15.52
38,10039,2022-02-08,1560,Electronics,East,1,428.42,0.26,COD,10,1.7,317.03
33,10034,2022-02-03,1313,Home,North,1,274.96,0.27,Card,9,3.0,200.72
23,10024,2022-01-24,1343,Clothing,East,1,180.34,0.23,Card,7,3.1,138.86
20,10021,2022-01-21,1661,Home,West,1,48.12,0.16,COD,8,4.7,40.42